### ISSUE TITLE
Uncaught TypeError: msnryWgArbeiten.masonry is not a function

### ISSUE THREAD

**Issue by suckkay** [philippfrenzel/yii2masonry#11]
hi, i dont understand how to fix this.

**Comment by philippfrenzel** [comment]
Hi, do you have a sample? This message doesn't help as stand alone?

**Comment by niektenhoopen** [comment]
@philippfrenzel I guess @suckkay means that the example with InfinityScroll in the readme is not working.

**Comment by philippfrenzel** [comment]
it should work! - i have it on the demo site here:

http://yii2fullcalendar.beeye.org/index.php/site/masonry

**Comment by niektenhoopen** [comment]
That example does not update through InfinityScroll, am I right?

I did not test it extensively enough but I guess it breaks because of the combination of Masonry and InfinityScroll and Pjax. I see that the Masonry variables get declared in the footer, after that IninityScroll requests more ListItems and updates the grid through Pjax, right? Could it be that the Masonry object somehow gets 'lost' during the Pjax call?

**Comment by philippfrenzel** [comment]
updated readme, thanks to @ishizune
